/*
为什么说xlh是神？
这个时候就要谈到犯下傲慢之罪的LTT了 
*/
#include<bits/stdc++.h>
using namespace std;
#define ri register int
#define rl register long long 
#define ll long long
template<typename T> inline void read(T &x){
    x=0;T w=1,ch=getchar();
    while(!isdigit(ch)&&ch!='-')ch=getchar();
    if(ch=='-')w=-1,ch=getchar();
    while(isdigit(ch))x=(x<<3)+(x<<1)+(ch^'0'),ch=getchar();
    x=x*w;
}
int main()
{
	freopen("kyouko.in","r",stdin);
	freopen("kyouko.out","w",stdout);
	ri n,T;
	read(T);
	while(T--)
	{
		read(n);
		if(n%2)	printf("YES\n");
		else printf("NO\n");
	}
}
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
//	cout<<"xlh will win"<<endl;
